# Generated by Django 3.1.5 on 2021-01-22 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User name')),
                ('is_github_user', models.BooleanField(default='false')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_name', models.CharField(max_length=100, verbose_name='Repository name')),
                ('date_of_creation', models.DateTimeField(verbose_name='Date of creation')),
                ('repository_url', models.URLField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.repositoryuser')),
            ],
        ),
        migrations.CreateModel(
            name='Committer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to='main_git_hub_api.repositoryuser')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='main_git_hub_api.repositoryuser')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.repository')),
            ],
        ),
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_massage', models.CharField(max_length=200, verbose_name='Comment text')),
                ('commit_date', models.DateTimeField(verbose_name='Date of commit')),
                ('committer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.committer')),
            ],
        ),
    ]
