# Generated by Django 3.1.5 on 2021-01-23 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_git_hub_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_github_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_github_collaborator', to='main_git_hub_api.repositoryuser')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_name', to='main_git_hub_api.repositoryuser')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.repository')),
            ],
        ),
        migrations.AlterField(
            model_name='commit',
            name='committer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.collaborator'),
        ),
        migrations.DeleteModel(
            name='Committer',
        ),
    ]
