# Generated by Django 3.1.5 on 2021-01-23 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_git_hub_api', '0002_auto_20210123_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.repositoryuser'),
        ),
    ]
