# Generated by Django 3.1.5 on 2021-02-01 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_git_hub_api', '0003_auto_20210123_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collaborator',
            options={'verbose_name': 'Соавтор', 'verbose_name_plural': 'Соавторы'},
        ),
        migrations.AlterModelOptions(
            name='commit',
            options={'ordering': ['-commit_date'], 'verbose_name': 'Коммит', 'verbose_name_plural': 'Коммиты'},
        ),
        migrations.AlterModelOptions(
            name='repository',
            options={'verbose_name': 'Репозиторий', 'verbose_name_plural': 'Репозитории'},
        ),
        migrations.AlterModelOptions(
            name='repositoryuser',
            options={'verbose_name': 'Польователь репозитория', 'verbose_name_plural': 'Пользователи репозитория'},
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='is_github_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='is_github_collaborator', to='main_git_hub_api.repositoryuser', verbose_name='Пользователь Github?'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator', to='main_git_hub_api.repositoryuser', verbose_name='Логин'),
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.repository', verbose_name='Репозиторий'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_date',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='commit_massage',
            field=models.CharField(max_length=200, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='commit',
            name='committer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.collaborator', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='date_of_creation',
            field=models.DateTimeField(verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_git_hub_api.repositoryuser', verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_name',
            field=models.CharField(max_length=100, verbose_name='Название репозитория'),
        ),
        migrations.AlterField(
            model_name='repository',
            name='repository_url',
            field=models.URLField(verbose_name='Ссылка на репозиторий'),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='is_github_user',
            field=models.BooleanField(default=False, verbose_name='Пользователь Github?'),
        ),
        migrations.AlterField(
            model_name='repositoryuser',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Логин'),
        ),
    ]
