# Generated by Django 3.1.5 on 2021-02-01 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_git_hub_api', '0004_auto_20210201_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repositoryuser',
            name='is_github_user',
        ),
        migrations.AlterField(
            model_name='collaborator',
            name='is_github_user',
            field=models.BooleanField(default=False, verbose_name='Пользователь Github?'),
        ),
    ]
